### ISSUE TITLE
Lines 243-251 of styles.css

### ISSUE THREAD

**Issue by lucymonie** [The-Authenticators/sohapp#48]
This is serious nit-picking but the styles on these lines are not as tidy as the others.

**Comment by marisid** [comment]
Lucy, this is an inevitable result of sass nesting (lines 312-325 in styles.scss - they look nicer before being compiled to css) to take advantage of grouping styles based on different levels of html elements.
```css
.payment-history__table {
  color: $main-white;
  border-spacing: 0;
  tr {
    td {
      padding-top: 0.5em;
      padding-bottom: 0.5em;
      border-bottom: 0.5px solid #aaa;
    }
    th {
      border-bottom: 2px solid #aaa;
    }
  }
}
```
